version: '2.0'
services:
  mtprotoproxy:
    build: .
    restart: restart
    ports:
        - "443:443/tcp"
        - "443:443/udp"
    volumes:
        - ./config.py:/home/tgproxy/config.py
        - ./mtprotoproxy.py:/home/tgproxy/mtprotoproxy.py
        - /etc/localtime:/etc/localtime:ro
    logging:
        driver: "json-file"
        options:
            max-file: "10"
            max-size: "10m"
#    mem_limit: 1024m
